model_class: Linear_MAE


encoder:

  hidden_size: 128

  masker:
    r_ratio: 0.1
    mask_mode: region

  stitcher:
    smoothing: true
    halfbin_X: 1
    smooth_w: 5
    n_channels_per_region: 32
